# Netlify configuration for Value Partner Next.js frontend

[build]
  # The Next.js project resides in the "frontend" directory
  base = "frontend"
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

  [build.environment]
    NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://api.yourdomain.com"
