{{- if .Values.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "value-investing-api.fullname" . }}-promtail-config
  labels:
    app: {{ include "value-investing-api.name" . }}
data:
  promtail.yaml: |
{{ .Values.loki.config | indent 4 }}
{{- end }}