replicaCount: 2

image:
  repository: ghcr.io/your-org/value-investing-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  DATABASE_URL: ""
  API_TIER: pro

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Bitnami PostgreSQL dependency values
postgresql:
  enabled: true
  auth:
    username: valueinvest
    password: changeme
    database: valueinvest

loki:
  enabled: true
  image: grafana/promtail:2.9.4
  config: |
    server:
      http_listen_port: 9080
    positions:
      filename: /run/promtail/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: container-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: valueinvest-api
              __path__: /var/log/containers/*$${HOSTNAME}*.log