"""add user table and consolidate user model

Revision ID: 86af28085e34
Revises: cec213bd7be0
Create Date: 2025-07-03 22:31:42.036047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86af28085e34'
down_revision: Union[str, None] = 'cec213bd7be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=False))
        batch_op.alter_column('email',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.drop_column('hashed_password')

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###
