name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pre-commit mypy safety black isort flake8 pytest pytest-cov
          pre-commit --version

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Run linters
        run: |
          black --check .
          isort --check .
          flake8

      - name: Security scan (Bandit)
        run: |
          pip install bandit
          bandit -q -r services models sdk data workbench

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt
        run: terraform -chdir=infra fmt -check -recursive

      - name: Terraform init (no backend)
        run: terraform -chdir=infra init -backend=false

      - name: Terraform validate
        run: terraform -chdir=infra validate

      - name: Run tests with coverage
        run: pytest --cov=. --cov-report=xml --cov-fail-under=80 -q

  trivy_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: fs
          ignore-unfixed: true
          exit-code: 1
          severity: CRITICAL,HIGH
          scanners: vuln

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/value-investing-api:latest

  dependency_check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@v3.1.2
        with:
          project: "value-investing-platform"
          path: "/workspace"
          format: "HTML"
          failOnCVSS: "7.0"
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: depcheck-report
          path: ${{ github.workspace }}/reports