name: Publish SDK

on:
  push:
    tags:
      - "sdk/v*.*.*"
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for release asset upload
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools setuptools_scm wheel

      - name: Build sdk wheel
        run: |
          cd sdk
          python -m build --wheel -o dist/

      - name: Upload wheel to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: sdk/dist/*.whl

      - name: Upload wheel artifact (tag push)
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: valueinvest_sdk_wheel
          path: sdk/dist/*.whl