version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.db
      MLFLOW_ARTIFACT_ROOT: /mlartifacts
    volumes:
      - ./mlartifacts:/mlartifacts